# Generated by Django 5.2.6 on 2025-09-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reselleruser',
            name='cupom_reseller',
            field=models.CharField(blank=True, max_length=10, verbose_name='cupom revendedor'),
        ),
    ]
